name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    # Set up Java environment for the next steps
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
          distribution: zulu
          java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: make
    - name: Run test with Gradle Wrapper
      run: make test
